In [ ]:
import os
import site
from pathlib import Path
import importlib  

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path = Path(os.getcwd())
site.addsitedir(path.parent)  

dataset_cleaning = importlib.import_module("utils.dataset_cleaning")

# the datasets that are returned are cleaned
df_aircraft = dataset_cleaning.clean_aircraft(
    '../../Resources/ACchar.xlsx'
    )

df_airport = dataset_cleaning.clean_airport(
    '../../Resources/training_set_airport_data.csv'
    )

df_geography = dataset_cleaning.clean_geography(
    '../../Resources/geographic_data.csv'
    )

df_weather = dataset_cleaning.clean_weather(
    '../../Resources/Weather_data.csv'
    )

dataset_joining = importlib.import_module("Hackathon-Eleven.utils.dataset_joining")

# joining cleaned datasets and combining them
# you do not have to list all datasets if you only want to join some of them
# but df_airport is the only one mandatory
merged_df = dataset_joining.join_datasets(df_airport, df_weather=df_weather,df_geography=df_geography, df_aircraft=df_aircraft)

In [2]:
#merged_df.info()

### Adding distance between stand and runway

In [3]:
pairs = pd.read_csv('/Users/valentinajerusalmi/Desktop/DSBA/YEAR_2/Hackaton/LocalFolder/new_pairs.csv')
pairs.columns = ['index','stand','runway','distance']
merged_df = pd.merge(merged_df, pairs,  how='left', left_on=['stand','runway'], right_on = ['stand','runway'])

In [4]:
#merged_df

### Adding target variable

In [5]:
merged_df.iloc[:,2] = pd.to_datetime(merged_df.iloc[:,2], errors = 'coerce')
merged_df.iloc[:,3] = pd.to_datetime(merged_df.iloc[:,3], errors = 'coerce')

variable = abs(merged_df.iloc[:,3] - merged_df.iloc[:,2])
merged_df['taxi_out']=variable.astype(int)/(6*10**10)

In [6]:
merged_df = merged_df.dropna()

### Remove outliers

In [7]:
merged_df = merged_df[merged_df['taxi_out']<500]

### Isolating the target variable

In [8]:
y = merged_df.pop('taxi_out')

In [9]:
X = merged_df

In [10]:
#X = X.dropna()

In [11]:
merged_df

,flight_datetime,aircraft_model,AOBT,ATOT,stand,runway,time_hourly,summary,temperature,dewPoint,...,tail_height_feet,wheelbase_feet,cockpit_to_main_gear_feet,main_gear_width,max_takeoff_weight,max_ramp_taxi_weight,parking_area_square_feet,number_gear_types_tandem,index,distance
0,2015-01-01 06:00:00,B737-800 WINGLETS,2015-01-01 05:56:00,2015-01-01 06:05:00,STAND_62,RUNWAY_4,2015-01-01 06:00:00,Cloudy,44.65,42.8,...,41.416667,51.166667,56.416667,22.958333,174200,174900,15205.458333,1,560.0,1150.0
1,2015-01-01 06:10:00,A320-100/200,2015-01-01 06:08:00,2015-01-01 06:18:00,STAND_153,RUNWAY_4,2015-01-01 06:00:00,Cloudy,44.65,42.8,...,39.63,41.47,50.2,29.36,171961,172842,13791.4476,1,651.0,1175.0
2,2015-01-01 06:15:00,A320-100/200,2015-01-01 06:08:00,2015-01-01 06:19:00,STAND_44,RUNWAY_2,2015-01-01 06:00:00,Cloudy,44.65,42.8,...,39.63,41.47,50.2,29.36,171961,172842,13791.4476,1,210.0,3150.0
3,2015-01-01 06:20:00,A320-100/200,2015-01-01 06:24:00,2015-01-01 06:36:00,STAND_7,RUNWAY_3,2015-01-01 06:00:00,Cloudy,44.65,42.8,...,39.63,41.47,50.2,29.36,171961,172842,13791.4476,1,339.0,3100.0
4,2015-01-01 06:20:00,A319,2015-01-01 06:14:00,2015-01-01 06:27:00,STAND_17,RUNWAY_2,2015-01-01 06:00:00,Cloudy,44.65,42.8,...,39.73,36.23,44.9,29.36,168653,169535,12420.9176,1,183.0,2800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536551,2018-12-31 21:15:00,A321-100/200,2018-12-31 20:59:00,2018-12-31 21:09:00,STAND_39,RUNWAY_4,2018-12-31 21:00:00,Clear,47.88,41.0,...,39.7,55.45,44.95,29.43,196211,197093,16337.8364,1,537.0,200.0
536552,2018-12-31 21:15:00,A350-900,2018-12-31 21:02:00,2018-12-31 21:20:00,STAND_150,RUNWAY_3,2018-12-31 21:00:00,Clear,47.88,41.0,...,57.31,94.045,99.265,42.22,617295,619279,46553.236667,2,482.0,1905.0
536553,2018-12-31 21:30:00,B787-900,2018-12-31 21:24:00,2018-12-31 21:38:00,STAND_77,RUNWAY_1,2018-12-31 21:00:00,Clear,47.88,41.0,...,56.083333,84.75,93.416667,38.916667,560000,561500,40649.9375,2,77.0,3550.0
536554,2018-12-31 21:50:00,A330-200,2018-12-31 22:27:00,2018-12-31 22:37:00,STAND_120,RUNWAY_1,2018-12-31 21:00:00,Clear,47.88,41.0,...,59.81,72.77,86.78,41.37,533519,535503,38293.9531,2,120.0,2500.0
536555,2018-12-31 22:10:00,B787-800 Dreamliner,2018-12-31 22:09:00,2018-12-31 22:29:00,STAND_49,RUNWAY_2,2018-12-31 22:00:00,Clear,48.26,41.0,...,56.083333,74.75,83.416667,38.083333,502500,503500,36704.9375,2,215.0,2825.0

In [12]:
X['flight_day']=X['flight_datetime'].dt.day_name()

In [13]:
X['flight_month']=X['flight_datetime'].dt.month_name()

In [14]:
val = (X['flight_datetime'].dt.hour % 24 + 4) // 4
val.replace({1: 'Late Night',
                      2: 'Early Morning',
                      3: 'Morning',
                      4: 'Noon',
                      5: 'Evening',
                      6: 'Night'}, inplace=True)

In [15]:
X['day_moment']=val

In [16]:
X = X.drop(['flight_datetime','aircraft_model','AOBT','ATOT','stand','index','time_hourly','manufacturer','full_aircraft_model'], axis=1)

In [17]:
X.columns

Index(['runway', 'summary', 'temperature', 'dewPoint', 'humidity', 'windSpeed',
       'windGust', 'windBearing', 'cloudCover', 'uvIndex', 'visibility',
       'Lat_runway', 'Lng_runway', 'Lat_stand', 'Lng_stand', 'engine class',
       'number_engines', 'approach_speed', 'wingtip_config', 'wingspan_feet',
       'length_feet', 'tail_height_feet', 'wheelbase_feet',
       'cockpit_to_main_gear_feet', 'main_gear_width', 'max_takeoff_weight',
       'max_ramp_taxi_weight', 'parking_area_square_feet',
       'number_gear_types_tandem', 'distance', 'flight_day', 'flight_month',
       'day_moment'],
      dtype='object')

In [18]:
X['number_engines'] = pd.to_numeric(X['number_engines'], downcast="float")
X['wingspan_feet'] = pd.to_numeric(X['wingspan_feet'], downcast="float")
X['length_feet'] = pd.to_numeric(X['length_feet'], downcast="float")
X['tail_height_feet'] = pd.to_numeric(X['tail_height_feet'], downcast="float")
X['wheelbase_feet'] = pd.to_numeric(X['wheelbase_feet'], downcast="float")
X['cockpit_to_main_gear_feet'] = pd.to_numeric(X['cockpit_to_main_gear_feet'], downcast="float")
X['main_gear_width'] = pd.to_numeric(X['main_gear_width'], downcast="float")
X['max_takeoff_weight'] = pd.to_numeric(X['max_takeoff_weight'], downcast="float")
X['max_ramp_taxi_weight'] = pd.to_numeric(X['max_ramp_taxi_weight'], downcast="float")
X['parking_area_square_feet'] = pd.to_numeric(X['parking_area_square_feet'], downcast="float")

In [19]:
X.select_dtypes('object').columns.tolist()

['runway',
 'summary',
 'engine class',
 'wingtip_config',
 'number_gear_types_tandem',
 'flight_day',
 'flight_month',
 'day_moment']

In [20]:
from sklearn.preprocessing import OneHotEncoder

# seleziona le features non numeriche
cat_column_names = X.select_dtypes('object').columns.tolist()
print(cat_column_names)
#cat_column_names.remove('Note')
#cat_column_names.remove('Years Manufactured')
#cat_column_names.remove('Wheelbase, ft')



# Fit dell'encoder sul train
ohe = OneHotEncoder(
    sparse=False,
    handle_unknown='ignore'  # mette tutti zero nel caso trovassimo classi sconosciute durante il "transform"
)
# converto in stringa, così anche eventuali nulli saranno categorie, poi faccio fit
ohe.fit(X[cat_column_names].astype(str))

# l'output di OneHotEncoder.transform sarà un numpy array, ma lo voglio ritrasformare in pandas dataframe
new_column_names = [
    f"{category} - {level}" for category, level_list in zip(cat_column_names, ohe.categories_)
    for level in level_list]

X_ohe = pd.DataFrame(
    ohe.transform(X[cat_column_names].astype(str)),
    index=X.index,
    columns=new_column_names)

# butto via le vecchie colonne categoriche e aggiungo le nuove
X = pd.concat([
    X.drop(cat_column_names, axis=1),
    X_ohe], axis=1)

['runway', 'summary', 'engine class', 'wingtip_config', 'number_gear_types_tandem', 'flight_day', 'flight_month', 'day_moment']

In [21]:
#merged_df['y']=y

### Remove outliers

In [22]:
#merged_df = merged_df[merged_df['y']<500]

In [24]:
#sns.pairplot(merged_df, x_vars = ['number_engines','wingspan_feet','length_feet','tail_height_feet','wheelbase_feet','cockpit_to_main_gear_feet',
#'main_gear_width', 'max_takeoff_weight','max_ramp_taxi_weight','parking_area_square_feet'], y_vars = 'y')

### Applying a scaling

In [25]:
X.select_dtypes('float').columns.tolist()

['temperature',
 'dewPoint',
 'humidity',
 'windSpeed',
 'windGust',
 'windBearing',
 'cloudCover',
 'uvIndex',
 'visibility',
 'Lat_runway',
 'Lng_runway',
 'Lat_stand',
 'Lng_stand',
 'approach_speed',
 'distance',
 'runway - RUNWAY_1',
 'runway - RUNWAY_2',
 'runway - RUNWAY_3',
 'runway - RUNWAY_4',
 'summary - Clear',
 'summary - Clouds and Wind',
 'summary - Cloudy',
 'summary - Dangerously Windy',
 'summary - Drizzle',
 'summary - Foggy',
 'summary - Possible Drizzle',
 'summary - Possible Light Rain',
 'summary - Rain',
 'summary - Rain and Wind',
 'engine class - Jet',
 'engine class - Turboprop',
 'wingtip_config - no winglets',
 'wingtip_config - winglets',
 'wingtip_config - wingtip fences',
 'number_gear_types_tandem - 1',
 'number_gear_types_tandem - 2',
 'number_gear_types_tandem - 3',
 'flight_day - Friday',
 'flight_day - Monday',
 'flight_day - Saturday',
 'flight_day - Sunday',
 'flight_day - Thursday',
 'flight_day - Tuesday',
 'flight_day - Wednesday',
 'flight_month - April',
 'flight_month - August',
 'flight_month - December',
 'flight_month - February',
 'flight_month - January',
 'flight_month - July',
 'flight_month - June',
 'flight_month - March',
 'flight_month - May',
 'flight_month - November',
 'flight_month - October',
 'flight_month - September',
 'day_moment - Early Morning',
 'day_moment - Evening',
 'day_moment - Late Night',
 'day_moment - Morning',
 'day_moment - Night',
 'day_moment - Noon']

In [26]:
#X = X.drop('index',axis=1)
#X = X.drop('taxi_out',axis=1)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
num_cols = ['temperature','dewPoint','humidity','windSpeed','windGust','windBearing','cloudCover',
 'uvIndex','visibility','Lat_runway','Lng_runway','Lat_stand','Lng_stand','approach_speed','distance']
X[num_cols] = scaler.fit_transform(X[num_cols])

In [28]:
X

,temperature,dewPoint,humidity,windSpeed,windGust,windBearing,cloudCover,uvIndex,visibility,Lat_runway,...,flight_month - May,flight_month - November,flight_month - October,flight_month - September,day_moment - Early Morning,day_moment - Evening,day_moment - Late Night,day_moment - Morning,day_moment - Night,day_moment - Noon
0,-0.834078,-0.435237,0.905336,0.746676,0.053825,0.151773,0.874827,-0.742019,0.108135,1.030571,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,-0.834078,-0.435237,0.905336,0.746676,0.053825,0.151773,0.874827,-0.742019,0.108135,1.030571,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,-0.834078,-0.435237,0.905336,0.746676,0.053825,0.151773,0.874827,-0.742019,0.108135,-0.625586,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,-0.834078,-0.435237,0.905336,0.746676,0.053825,0.151773,0.874827,-0.742019,0.108135,0.909388,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,-0.834078,-0.435237,0.905336,0.746676,0.053825,0.151773,0.874827,-0.742019,0.108135,-0.625586,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
536551,-0.542535,-0.633081,-0.113337,0.136340,2.152154,0.692994,1.743393,-0.742019,0.408057,1.030571,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
536552,-0.542535,-0.633081,-0.113337,0.136340,2.152154,0.692994,1.743393,-0.742019,0.408057,0.909388,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
536553,-0.542535,-0.633081,-0.113337,0.136340,2.152154,0.692994,1.743393,-0.742019,0.408057,-1.312284,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
536554,-0.542535,-0.633081,-0.113337,0.136340,2.152154,0.692994,1.743393,-0.742019,0.408057,-1.312284,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
536555,-0.508235,-0.633081,-0.177004,0.492941,2.152154,0.890747,1.743393,-0.742019,0.408057,-0.625586,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [30]:
import numpy as np
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X_train, y_train)
reg.score(X_test, y_test)

0.10578699487039989

In [33]:
from sklearn.ensemble import GradientBoostingRegressor
xgb = GradientBoostingRegressor(random_state=0)
xgb.fit(X_train, y_train)
xgb.score(X_test, y_test)

0.1252099865776959