In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 30)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [7]:
dir_folder = 'C:\\Users\\Lucas\\Documents\\GitHub\\'
df_w = pd.read_csv(dir_folder + '\\2. Weather data\\training_set_weather_data.csv')
df_w

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Lucas\\Documents\\GitHub\\\\2. Weather data\\training_set_weather_data.csv'

In [15]:
df_a = pd.read_excel('C:\\Data\\Hackathon\\1. AC characteristics\\ACchar.xlsx', sheet_name='test')
df_a

,Date Completed,Manufacturer,A320-100,Physical Class (Engine),# Engines,AAC,ADG,TDG,Approach Speed\n(Vref),Wingtip Configuration,"Wingspan, ft","Length, ft","Tail Height, ft\n(@ OEW)","Wheelbase, ft",Cockpit to Main Gear (CMG),MGW\n(Outer to Outer),MTOW,Max Ramp\nMax Taxi,Main Gear Config,ICAO Code,Wake Category,ATCT Weight Class,Years Manufactured,Note,"Parking Area (WS x Length), sf"
0,2018-07-03 00:00:00,Acro Sport,Acro Sport,Piston,1,A,I,1A,55.9,no winglets,19.5833,17.5,6,tbd,tbd,tbd,1350,1520,S,ACRO,L,Small Eqpt,tbd,tbd,342.708
1,2018-06-01 00:00:00,Acro Sport,Acro Sport II,Piston,1,A,I,1A,59.8,no winglets,21.6667,18.8542,6.64583,tbd,tbd,tbd,1520,1520,S,ACR2,L,Small Eqpt,tbd,tbd,408.507
2,2018-07-03 00:00:00,Acro Sport,Cougar,Piston,1,A,I,1A,45.5,no winglets,20.5,18.9167,5.5,tbd,tbd,tbd,1250,1250,S,COUG,L,Small Eqpt,tbd,tbd,387.792
3,2018-07-03 00:00:00,Acro Sport,Junior Ace,Piston,1,A,I,1A,49.4,no winglets,26.5,18,tbd,tbd,tbd,tbd,1225,1225,S,JACE,L,Small Eqpt,tbd,tbd,477
4,2018-07-03 00:00:00,Acro Sport,Super Ace,Piston,1,A,I,1A,49.4,no winglets,27.2917,18.5,6.5,tbd,tbd,tbd,1030,1030,S,SACE,L,Small Eqpt,tbd,tbd,504.896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,NaN,Zlin,Zlin Z-50,tbd,tbd,No Value,No Value,tbd,NaN,tbd,NaN,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,BA11,M,tbd,tbd,tbd,NaN
2760,NaN,Zlin,Zlin Z-526 Akrobat,tbd,tbd,No Value,No Value,tbd,NaN,tbd,NaN,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,NaN
2761,NaN,Zlin,Zlin Z-526 Trener Master,tbd,tbd,No Value,No Value,tbd,NaN,tbd,NaN,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,NaN
2762,NaN,Zlin,Zlin Z-626,tbd,tbd,No Value,No Value,tbd,NaN,tbd,NaN,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,tbd,NaN
2763,tbd,Zlin,Zlin Z-726 Universal,tbd,tbd,B,II,tbd,97.0,tbd,49.08,tbd,15,tbd,tbd,tbd,6750,tbd,tbd,AC50,tbd,Small Eqpt,tbd,tbd,NaN

In [28]:
#df_apt_geo = pd.read_csv("C:\\Data\\Hackathon\\0. Airport data\\geographic_data.csv")
df_apt_geo['Lat_runway'].unique()

array([54.75530667, 54.75712   , 54.76117333, 54.76149333])

In [21]:
df_apt_time = pd.read_csv('C:\\Data\\Hackathon\\0. Airport data\\training_set_airport_data.csv')
df_apt_time

,Flight Datetime,Aircraft Model,AOBT,ATOT,Stand,Runway
0,1/1/2015 6:00,B737-800 WINGLETS,1/1/2015 5:56,1/1/2015 6:05,STAND_62,RUNWAY_4
1,1/1/2015 6:10,A320-100/200,1/1/2015 6:08,1/1/2015 6:18,STAND_153,RUNWAY_4
2,1/1/2015 6:15,A320-100/200,1/1/2015 6:08,1/1/2015 6:19,STAND_44,RUNWAY_2
3,1/1/2015 6:20,A320-100/200,1/1/2015 6:24,1/1/2015 6:36,STAND_7,RUNWAY_3
4,1/1/2015 6:20,A319,1/1/2015 6:14,1/1/2015 6:27,STAND_17,RUNWAY_2
...,...,...,...,...,...,...
543808,12/31/2018 21:15,A350-900,12/31/2018 21:02,12/31/2018 21:20,STAND_150,RUNWAY_3
543809,12/31/2018 21:30,B787-900,12/31/2018 21:24,12/31/2018 21:38,STAND_77,RUNWAY_1
543810,12/31/2018 21:50,A330-200,12/31/2018 22:27,12/31/2018 22:37,STAND_120,RUNWAY_1
543811,12/31/2018 22:10,B787-800 Dreamliner,12/31/2018 22:09,12/31/2018 22:29,STAND_49,RUNWAY_2
543812,12/31/2018 23:55,B787-900,12/31/2018 23:58,1/1/2019 0:11,STAND_12,RUNWAY_4

,Flight Datetime,Aircraft Model,AOBT,ATOT,Stand,Runway
0,1/1/2015 6:00,B737-800 WINGLETS,1/1/2015 5:56,1/1/2015 6:05,STAND_62,RUNWAY_4
1,1/1/2015 6:10,A320-100/200,1/1/2015 6:08,1/1/2015 6:18,STAND_153,RUNWAY_4
2,1/1/2015 6:15,A320-100/200,1/1/2015 6:08,1/1/2015 6:19,STAND_44,RUNWAY_2
3,1/1/2015 6:20,A320-100/200,1/1/2015 6:24,1/1/2015 6:36,STAND_7,RUNWAY_3
4,1/1/2015 6:20,A319,1/1/2015 6:14,1/1/2015 6:27,STAND_17,RUNWAY_2
...,...,...,...,...,...,...
543808,12/31/2018 21:15,A350-900,12/31/2018 21:02,12/31/2018 21:20,STAND_150,RUNWAY_3
543809,12/31/2018 21:30,B787-900,12/31/2018 21:24,12/31/2018 21:38,STAND_77,RUNWAY_1
543810,12/31/2018 21:50,A330-200,12/31/2018 22:27,12/31/2018 22:37,STAND_120,RUNWAY_1
543811,12/31/2018 22:10,B787-800 Dreamliner,12/31/2018 22:09,12/31/2018 22:29,STAND_49,RUNWAY_2
543812,12/31/2018 23:55,B787-900,12/31/2018 23:58,1/1/2019 0:11,STAND_12,RUNWAY_4